# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комметарий')),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2018, 1, 14, 22, 20, 59, 968662))),
            ],
            options={
                'verbose_name': 'Комметарий',
                'ordering': ['comment_date'],
                'verbose_name_plural': 'Комметарии',
            },
        ),
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=20, verbose_name='Заноловок статьи')),
                ('post_text', models.CharField(max_length=255, verbose_name='Текст поста: ')),
                ('post_likes', models.IntegerField(default=0, verbose_name='Понравилось: ')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2018, 1, 14, 22, 20, 59, 967662))),
            ],
            options={
                'verbose_name': 'Пост',
                'ordering': ['post_date', 'post_likes', 'post_title'],
                'verbose_name_plural': 'Список постов',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostMessage'),
        ),
    ]
