# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 21:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180114_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 0, 41, 34, 728841)),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 0, 41, 34, 728841)),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='post_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_massage', to=settings.AUTH_USER_MODEL),
        ),
    ]
