# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180115_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmessage',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Список постов'},
        ),
        migrations.RemoveField(
            model_name='postmessage',
            name='post_user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 0, 55, 35, 685648)),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 0, 55, 35, 685648)),
        ),
    ]
