# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 22:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20180115_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='post_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_massage', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 1, 7, 194942)),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 1, 7, 194942)),
        ),
    ]
