# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180115_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 13, 29, 25, 141950)),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 13, 29, 25, 141950)),
        ),
    ]
