# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 12:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20180115_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_massage', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 15, 18, 16, 632596)),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 15, 18, 16, 632596)),
        ),
    ]
