# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 14:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20180115_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date'], 'verbose_name': 'Комметарий', 'verbose_name_plural': 'Комметарии'},
        ),
        migrations.AlterModelOptions(
            name='postmessage',
            options={'ordering': ['date', 'likes', 'title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Список постов'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='postmessage',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='postmessage',
            name='post_likes',
        ),
        migrations.RemoveField(
            model_name='postmessage',
            name='post_text',
        ),
        migrations.RemoveField(
            model_name='postmessage',
            name='post_title',
        ),
        migrations.RemoveField(
            model_name='postmessage',
            name='post_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 17, 0, 55, 633306)),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_massage', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 17, 0, 55, 630311)),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Понравилось'),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='text',
            field=models.CharField(default=2, max_length=255, verbose_name='Текст поста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmessage',
            name='title',
            field=models.CharField(default=34, max_length=20, verbose_name='Заголовок статьи'),
            preserve_default=False,
        ),
    ]
